version: '3.2'

services:

### OMS SERVICE REGISTRY #######################################
    oms-central-frontend:
        build:
            context: ./$PATH_OMS_CENTRAL_FRONTEND/oms-central-frontend/
            dockerfile: ./Dockerfile.dev
        volumes:
            - "./$PATH_OMS_CENTRAL_FRONTEND/../:/usr/app/src"
            - "centralfrontend:/usr/app/dist"
            - "centralfrontend-build:/usr/app/build"

    oms-central-frontend-nginx:
        build:
            context: ./$PATH_OMS_CENTRAL_FRONTEND/oms-central-frontend-nginx/
            dockerfile: ./Dockerfile.dev
        volumes:
            - "centralfrontend:/usr/app/dist:ro"
        labels:
            - "traefik.frontend.rule=HostRegexp:{domain:[a-z0-9.]+};PathPrefix:/"
            - "traefik.frontend.priority=11"
            - "traefik.port=80"
            - "traefik.backend=oms-central-frontend"
            - "traefik.enable=true"
            - "registry.status=status.json"
            - "registry.modules=getModules.json"

volumes:
    centralfrontend:
        driver: "local"
    centralfrontend-build:
        driver: "local"

networks:
  default:
    external:
      name: OMS
